# Generated by Django 4.1.3 on 2022-12-21 17:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0006_teachersforstudent'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='teachers',
        ),
    ]
