# Generated by Django 4.1.3 on 2022-12-22 08:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0007_remove_student_teachers'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teachersforstudent',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='student', to='school.student'),
        ),
        migrations.AlterField(
            model_name='teachersforstudent',
            name='teacher',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='teacher', to='school.teacher'),
        ),
    ]
