# Generated by Django 4.1.3 on 2022-12-03 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('phones', '0002_remove_phone_image_remove_phone_lte_exists_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='phone',
            name='image',
            field=models.ImageField(default=None, upload_to=''),
        ),
        migrations.AddField(
            model_name='phone',
            name='lte_exists',
            field=models.BooleanField(default=None),
        ),
        migrations.AddField(
            model_name='phone',
            name='price',
            field=models.IntegerField(default=None),
        ),
        migrations.AddField(
            model_name='phone',
            name='release_date',
            field=models.DateField(default=None),
        ),
    ]
