# Generated by Django 4.1.3 on 2022-12-03 11:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('phones', '0003_phone_image_phone_lte_exists_phone_price_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='phone',
            name='image',
        ),
    ]
