# Generated by Django 4.1.3 on 2022-12-03 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('phones', '0004_remove_phone_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='phone',
            name='image',
            field=models.ImageField(default=None, upload_to=''),
        ),
    ]
