# Generated by Django 4.1.3 on 2022-12-04 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('phones', '0006_phone_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='phone',
            name='id',
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
    ]
